### PR TITLE
Closes #361

### LINKED ISSUE #361: Once a transaction is completed, navigate the user to the transactions tab
Currently, after a user confirms their send transaction, a green confirmation modal shows up at the bottom but the user stays on the send tab. To avoid double spending and confusion, once the user confirms the transaction, navigate them from the send tab to the transactions tab and show a pending transaction.  

Updated flow: 
1. Enter address and amount
2. Confirm transaction details
3. View pending transaction on the transaction tab with the green confirmation modal

### PR DESCRIPTION
**Pull request by Aeesh**

### CODE REVIEW

**Comment by dariuszsobkowicz** [comment]
@vishakh @Aeesh @navi-arneja 
question, if transaction fail do we still want to navigate to transactions tab?

**Comment by navi-arneja** [comment]
> @vishakh @Aeesh @navi-arneja
> question, if transaction fail do we still want to navigate to transactions tab?

I think if the transaction fails, we should keep the user on the send tab with an error modal to prevent them from thinking the transaction went through, even if it didn't.

**Comment by Aeesh** [comment]
Uploading Tezori 2021-05-28 12-55-15.mp4…



> > @vishakh @Aeesh @navi-arneja
> > question, if transaction fail do we still want to navigate to transactions tab?
> 
> I think if the transaction fails, we should keep the user on the send tab with an error modal to prevent them from thinking the transaction went through, even if it didn't.

Yes, it only goes to the transaction tab upon a successful transaction. I'd attached a screencast earlier to show that, but it must have failed. Adding it back now

**Comment by Aeesh** [comment]
https://user-images.githubusercontent.com/47456520/120019014-d52c6200-bfdf-11eb-9c38-077ebff16604.mp4

**Review by dariuszsobkowicz — APPROVED** [review]

**Pull request closed without merging**
